### ISSUE TITLE
Why are underscores removed?

### ISSUE THREAD

**Issue by roedoejet** [pavelsof/ipatok#5]
Hi there,

Thanks for this amazing library! I'm wondering why the tokenise method replaces underscores with space `words = string.strip().replace('_', ' ').split()`? This is not parameterized and even with `unknown=True` and `strict=False` these are removed. Our use case needs to preserve underscores. Happy to submit a PR if that would be helpful, I just want to understand why this is happening.

Thanks!

**Comment by pavelsof** [comment]
Thank you! I am happy you find the package useful! :green_heart: 

To be honest, I cannot remember why this is the case. There is a [commit from 2017](https://github.com/pavelsof/ipatok/commit/29222d7e456fe9e71ff4b4904377d42c9c0a40fd) where I explicitly add the underscore as a word boundary char; I guess because of a dataset I was working with at the time.

At any rate, you are right, underscores should be treated just like any other unknown char; and the `unknown` and `strict` flags should indeed have a say in how it is handled. You are welcome to submit a PR if you have the time to! If not, I will take care of it and make a new release next weekend. Thank you for raising this issue!

**Comment by pavelsof** [comment]
Done, the latest version handles underscores as any other unknown character. Thank you again for raising this issue! (:

**Comment by roedoejet** [comment]
Thanks so much @pavelsof ! Sorry I didn't get around to making the PR myself - you were too quick. It's much appreciated though. Thanks again for the great library.
